[workspace]
members = [
    "question_21",
    "question_26",
    "question_27",
    "question_28",
    "question_35",
    "question_38",
    "question_53",
    "question_80",
    "question_83",
    "question_136",
    "question_137",
    "question_191",
    "question_268",
    "question_349",
    "question_1047",
    "question_1603",
    "question_1846",
]

[profile.dev]
split-debuginfo = "unpacked"
