[workspace]
members = [
    "21",
    "26",
    "27",
    "28",
    "35",
    "38",
    "53",
    "56",
    "80",
    "83",
    "136",
    "137",
    "191",
    "242",
    "268",
    "349",
    "414",
    "724",
    "1047",
    "1603",
    "1846",
]

[profile.dev]
split-debuginfo = "unpacked"
